org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_loader=javafml
mod_group_id=me.zhenxin.zmusic
mod_id=zmusic
mod_name=ZMusic Mod
mod_license=GPL-3.0-only
mod_authors=ZhenXin
mod_description=Powerful Music System

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.42
neo_version_range=[21.1.42,)

loader_version_range=[4,)